api:
  image: flipstone/glados-dev:20150919-0900

  volumes:
    - .:/glados
  ports:
    - 8000:8000

  working_dir: /glados
  links:
    - db:db

  command: sh -c 'cabal update && cabal install -j && ./.cabal-sandbox/bin/glados'

db:
  image: postgres:9.3.6

  expose:
    - 5432

  ports:
    - 54321:5432

  volumes:
    - ./initdb.d:/docker-entrypoint-initdb.d

  environment:
    POSTGRES_PASSWORD: master

