production:
  task_definition_template: task.yml
  cluster_name: default
  service_name: glados-prod
  service_role: ecsServiceRole
  region: NorthVirginia
  desired_count: 2
  health_check_timeout_seconds: 420
  load_balancers:
    - load_balancer_name: glados-elb
      container_name: api
      container_port: 8000
  context:
    task_family: glados
    config_bucket: flipstone-glados
    config_key: config/20150921-0700.json

