#!/bin/sh
set -e

. $DEPLOY_ROOT/settings
$SUDO docker run --name $CONTAINER_NAME \
                 --restart=always \
                 -p $HOST_PORT:$CONTAINER_PORT \
                 -d \
                 -v $DEPLOY_ROOT:/data \
                 $REPO:$CURRENT_VERSION

