#!/bin/sh

set -e

VERSION=$1

if [ "$VERSION" = "" ]; then
  echo "Please specify the version to build."
  exit 1
fi;

echo ""
echo "=== Building Docker Container ==="

cp .cabal-sandbox/bin/glados containers/release/glados

docker pull flipstone/glados:latest
docker build -t flipstone/glados:$VERSION containers/release
docker tag -f flipstone/glados:$VERSION flipstone/glados:latest


