#!/bin/sh

set -e

ENVIRONMENT=$1

if [ "$ENVIRONMENT" = "" ]; then
  echo "Please specify the environment you would like to deploy to"
  exit 1
fi;

VERSION=$2

if [ "$VERSION" = "" ]; then
  echo "Please specify the container version you'd like to deploy"
  exit 1
fi;

if [ "$CONFIG_ACCESS_KEY_ID" == "" ]; then
  echo "CONFIG_ACCESS_KEY_ID must be set in your environment!"
  exit 1;
fi;

if [ "$CONFIG_SECRET_ACCESS_KEY" == "" ]; then
  echo "CONFIG_SECRET_ACCESS_KEY must be set in your environment!"
  exit 1;
fi;


if [ "$CIRCLECI" = "" ]; then
  DOCKER_RM="--rm"
fi;

./tasks/retriable 3 docker pull flipstone/haitatsu:0.1.4

./tasks/haitatsu \
  -e $ENVIRONMENT \
  -c version=$VERSION,config_access_key_id=$CONFIG_ACCESS_KEY_ID,config_secret_access_key=$CONFIG_SECRET_ACCESS_KEY \
  deliver

