#!/bin/sh

set -e

ENVIRONMENT=$1

if [ "$ENVIRONMENT" = "" ]; then
  echo "Please specify the environment you would like to deploy to"
  exit 1
fi;

VERSION=$2

if [ "$VERSION" = "" ]; then
  echo "Please specify the container version you'd like to deploy"
  exit 1
fi;


if [ "$CIRCLECI" = "" ]; then
  DOCKER_RM="--rm"
fi;

./tasks/retriable 3 docker pull flipstone/haitatsu:0.1.4

./tasks/haitatsu \
  -e $ENVIRONMENT \
  -c version=$VERSION \
  deliver

